// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPjO8QQmiEHMAvcLOj8uO_iDg2F-2qNx4',
    appId: '1:106581407588:web:5e5bb02cec57b997606c71',
    messagingSenderId: '106581407588',
    projectId: 'fospresence',
    authDomain: 'fospresence.firebaseapp.com',
    storageBucket: 'fospresence.appspot.com',
    measurementId: 'G-WYCP2SERPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyBQLZIiuOneXfnoktgcErmwII_jW2REw',
    appId: '1:106581407588:android:e37a04f4472683d9606c71',
    messagingSenderId: '106581407588',
    projectId: 'fospresence',
    storageBucket: 'fospresence.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpPxpeXO4_iDOT0zNnE0T3xebwFWg-cZI',
    appId: '1:106581407588:ios:e9581bbfe04ee1a3606c71',
    messagingSenderId: '106581407588',
    projectId: 'fospresence',
    storageBucket: 'fospresence.appspot.com',
    iosBundleId: 'com.example.fospresence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpPxpeXO4_iDOT0zNnE0T3xebwFWg-cZI',
    appId: '1:106581407588:ios:87074309921793d4606c71',
    messagingSenderId: '106581407588',
    projectId: 'fospresence',
    storageBucket: 'fospresence.appspot.com',
    iosBundleId: 'com.example.fospresence.RunnerTests',
  );
}
